### ISSUE TITLE
Please remember increasing versionCode

### ISSUE THREAD

**Issue by IzzySoft** [clightning4j/lamp#102]
Version 3.5 (released 2 days ago) still has versionCode set to 34 – as has version 3.4 from last year, hence Android won't see it as an update. Please remember to increase versionCode directly before releasing a new version :wink: Thanks!

**Comment by vincenzopalazzo** [comment]
Ops! @IzzySoft we had one year to increase the number but we missed this opportunity, my fault.

We will fix it, thanks to reporting it

**Comment by IzzySoft** [comment]
> we had one year to increase the number but we missed this opportunity

:rofl: Guess you couldn't decide on the number – the usual problem of committees… :speak_no_evil:

> We will fix it, thanks to reporting it

Gladly, and thanks! Once it's up my updater will fetch it, as usual, and it will not only [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.lvaccaro.lamp) but also be announced as available update to the users of my repo then.

Besides, if you wish to link there, I also [have a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) you can use for that if you want…

**Comment by vincenzopalazzo** [comment]
> rofl Guess you couldn't decide on the number – the usual problem of committees… speak_no_evil

Yep, it is the correct moment to automate the process to get the version of the app.

>Gladly, and thanks! Once it's up my updater will fetch it, as usual, and it will not only show up here but also be announced as available update to the users of my repo then.
Besides, if you wish to link there, I also have a badge you can use for that if you want…

This is pretty amazing, We will add all info to the readme.

**Comment by IzzySoft** [comment]
> Yep, it is the correct moment to automate the process to get the version of the app.

Right, let the bots decide :rofl:

> We will add all info to the readme.

Cool, thanks! Looking forward to that.

**Comment by vincenzopalazzo** [comment]
Hi @IzzySoft,

The new version is on master :-) with the version number fix.

The only drawback and that we changed the organization to maintains all in one place, sorry for that.

**Comment by IzzySoft** [comment]
Nice to see my badge on the front page, thanks! Looking forward to the next tag then with the version number fix included. I didn't quite get what you apologize for: what organization did change?

**Comment by vincenzopalazzo** [comment]
what organization did change?

We migrate from [lightningamp](https://github.com/lightningamp) to [clightning4j](https://github.com/clightning4j)

**Comment by IzzySoft** [comment]
Well… and aren't we at the new location here already? So what changes, from here?

**Comment by vincenzopalazzo** [comment]
>Well… and aren't we at the new location here already? So what changes, from here?

From a user point of view only the URL.

**Comment by IzzySoft** [comment]
Ah, now I get it: the metadata on my end needed to be updated. Right. Done that now (will take effect with the next sync tomorrow). Thanks for pointing out! Fix took less than a minute :smile:

**Comment by vincenzopalazzo** [comment]
Sorry for that!

**Comment by IzzySoft** [comment]
No prob, don't worry – happens all the time. I often (not always) notice the redirect and update then – usually when my crawler suggests me to add an app I already have added :laughing: In this case you've been faster with telling me, which is good. Thanks a lot!
