### ISSUE TITLE
APK at release 2.5 identifies as 3.4

### ISSUE THREAD

**Issue by IzzySoft** [clightning4j/lamp#104]
Looks like you forgot to adjust `versionCode` and `versionName` before building the APK for v3.5:

    package: name='com.lvaccaro.lamp' versionCode='34' versionName='3.4'

Can you please fix that and replace the APK? The current one wouldn't be considered an update by Android and thus not suggested to the user. Thanks!

**Comment by vincenzopalazzo** [comment]
Hello @IzzySoft,

I can consider this fixed in #102 ?

https://github.com/clightning4j/lamp/blob/41e8e736c5c4b9288d73fb6579e26e03a3778393/app/build.gradle#L13-L14

**Comment by IzzySoft** [comment]
I consider it fixed once the APK was replaced at that tag – or a newer tag was created with a matching APK. Because until then, my updater downloads that APK every day just to throw it away when finding out it's not the proper version…

Sorry for opening a new issue – had I seen the previous one I hadn't done it. That's the problem with closed issues, hence better not close until the fix is applied and available :wink: Mind to replace the APK so we're rid of the issue?

**Comment by vincenzopalazzo** [comment]
Hi @IzzySoft,

Sure, in the next few days we will update tha apk. Sorry for that.

**Comment by IzzySoft** [comment]
Thanks a lot! Can we leave this issue here open until then so nagging folks like me don't open new ones each other day? :speak_no_evil: :see_no_evil:

**Comment by vincenzopalazzo** [comment]
@IzzySoft it is correct left it open, is an apk bug that we need to fix. You are not nagging at all.

I take your playstore as a black box without think if the apk was a problem. My fault :smile_cat:

**Comment by IzzySoft** [comment]
Thanks a lot! :hugs:
